name: Build and Publish Container

on:
  workflow_dispatch

jobs:
  build:
    name: Build

    runs-on: ubuntu-20.04


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Define Container Tag
        run: |
          echo "container_tag_latest=ghcr.io/${GITHUB_REPOSITORY}:latest" >> $GITHUB_ENV
          echo "container_tag_sha=ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Container
        run: |
          docker build . \
            --build-arg revision=$GITHUB_SHA \
            --build-arg version=$GITHUB_RUN_NUMBER \
            --tag $container_tag_latest \
            --tag $container_tag_sha
        shell: bash

      # Publish the container if we successfully build under Linux
      - name: Sign in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.OCTODEMOBOT_GHPR_TOKEN }}
          registry: ghcr.io
      
      - name: Publish Docker image
        id: container_publish
        run: |
          docker push $container_tag
